# docker-compose.yaml
version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: kasko_md
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www

  web:
    image: nginx:stable
    container_name: kasko_md_web
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./:/var/www
      - ./docker/app.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
